# Task-1 for Codesoft



#Import necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import GridSearchCV


#Load the dataset

In [2]:
df = pd.read_csv('/content/sample_data/Titanic-Dataset.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# Data Exploration

In [3]:
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


In [5]:
print(df.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  


# Data Cleaning

In [15]:
# Check if the columns exist before dropping
print(df.columns)

# If the columns exist, proceed with the drop, ensuring correct capitalization
if 'Cabin' in df.columns and 'Ticket' in df.columns:
    df.drop(columns=['Cabin','Ticket'], inplace=True)
else:
    print("One or both of 'Cabin' and 'Ticket' columns are not found in the DataFrame.")
    # Handle the case where the columns are not found, e.g., investigate why they are missing
df.head()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Fare', 'Embarked'],
      dtype='object')
One or both of 'Cabin' and 'Ticket' columns are not found in the DataFrame.


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch     Fare Embarked  
0      0   7.2500        S  
1      0  71.2833        C  
2      0   7.9250        S  
3      0  53.1000        S  
4      0   8.0500        S

In [17]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch     Fare Embarked  
0      0   7.2500        S  
1      0  71.2833        C  
2      0   7.9250        S  
3      0  53.1000        S  
4      0   8.0500        S

# Convert categorical variables to numeric

In [18]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

      Fare  Embarked  
0   7.2500         2  
1  71.2833         0  
2   7.9250         2  
3  53.1000         2  
4   8.0500         2

In [22]:
df['Familysize'] = df['SibSp'] + df["Parch"] + 1
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

      Fare  Embarked  Familysize  
0   7.2500         2           2  
1  71.2833         0           2  
2   7.9250         2           1  
3  53.1000         2           2  
4   8.0500         2           1

# Data Splitting

In [23]:
x = df.drop(columns=['Survived','Name','PassengerId'])
y  = df['Survived']
x_trian, x_test ,y_trian, y_test = train_test_split(x,y,test_size = 0.6 ,random_state=42 )

In [25]:
reg = LogisticRegression()
reg.fit(x_trian,y_trian)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [26]:
rf = RandomForestClassifier()
rf.fit(x_trian,y_trian)

RandomForestClassifier()

In [27]:
svm = SVC()
svm.fit(x_trian,y_trian)

SVC()

# Model Evaluation

In [31]:
models = [reg,rf,svm]
for model in models:
  y_pred = model.predict(x_test)
  print(f"Model : {model}")
  print(f"Accuracy : {accuracy_score(y_test,y_pred)} ")
  print(classification_report(y_test,y_pred))
  print(confusion_matrix(y_test,y_pred))


Model : LogisticRegression()
Accuracy : 0.8168224299065421 
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       324
           1       0.80      0.72      0.76       211

    accuracy                           0.82       535
   macro avg       0.81      0.80      0.80       535
weighted avg       0.82      0.82      0.81       535

[[286  38]
 [ 60 151]]
Model : RandomForestClassifier()
Accuracy : 0.7906542056074767 
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       324
           1       0.73      0.73      0.73       211

    accuracy                           0.79       535
   macro avg       0.78      0.78      0.78       535
weighted avg       0.79      0.79      0.79       535

[[268  56]
 [ 56 155]]
Model : SVC()
Accuracy : 0.6560747663551402 
              precision    recall  f1-score   support

           0       0.65      0.94      0.77       324
           1       0.7

In [32]:
param_grid ={
    'n_estimators' : [10,20,30,40,50,60,70,80,90,100],
    'max_depth' : [2,3,4,5,6,7,8,9,10],
}

In [33]:
grid_search = GridSearchCV(estimator=rf,param_grid=param_grid,cv=5, n_jobs=-1, verbose =2 )
grid_search.fit(x_trian,y_trian)
print(f"Best parameters : {grid_search.best_params_}")
best_rf = grid_search.best_estimator_

Fitting 5 folds for each of 90 candidates, totalling 450 fits
Best parameters : {'max_depth': 8, 'n_estimators': 50}


# Final Evaluation with Best Model

In [35]:
y_pred_best = best_rf.predict(x_test)
print(f"Accuracy with Best RF: {accuracy_score(y_test,y_pred_best)}")
print(classification_report(y_test,y_pred_best))
print(confusion_matrix(y_test,y_pred_best))


Accuracy with Best RF: 0.8168224299065421
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       324
           1       0.80      0.71      0.75       211

    accuracy                           0.82       535
   macro avg       0.81      0.80      0.80       535
weighted avg       0.82      0.82      0.81       535

[[287  37]
 [ 61 150]]


** Save the model for future use**

In [36]:
import joblib
joblib.dump(best_rf,'model.pkl')

['model.pkl']